BOARD_TAG    = uno
ARDUINO_PORT = /dev/ttyUSB0
ARDUINO_LIBS = SoftwareSerial FastLed SimpleTimer stringQueue lsem l298nem CarEngine

#USER_LIB_PATH = $(realpath ./lib)
USER_LIB_PATH = $(realpath ../SCS/arduino)

AVRDUDE_ARD_BAUDRATE = 115200

ARDUINO_DIR  = /usr/share/arduino

include $(ARDUINO_DIR)/Arduino.mk


